CREATE TABLE `community_event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(191) NOT NULL,
  `category` VARCHAR(191) NOT NULL,
  `description` TEXT NOT NULL,
  `imageUrl` VARCHAR(2048) NULL,
  `status` ENUM('Pending', 'Approved', 'Rejected', 'Cancelled', 'Completed') NOT NULL DEFAULT 'Pending',
  `eventDate` VARCHAR(191) NOT NULL,
  `startTime` VARCHAR(191) NOT NULL,
  `endTime` VARCHAR(191) NOT NULL,
  `multiDay` BOOLEAN NOT NULL DEFAULT FALSE,
  `endDate` VARCHAR(191) NULL,
  `recurring` BOOLEAN NOT NULL DEFAULT FALSE,
  `frequency` VARCHAR(191) NULL,
  `registrationOpens` VARCHAR(191) NULL,
  `registrationCloses` VARCHAR(191) NULL,
  `templeName` VARCHAR(191) NOT NULL,
  `hallName` VARCHAR(191) NULL,
  `address` VARCHAR(191) NULL,
  `mapsLink` VARCHAR(2048) NULL,
  `onlineLink` VARCHAR(2048) NULL,
  `attendees` INT NOT NULL DEFAULT 0,
  `organizer_id` INT NOT NULL,
  `reviewed_by_id` INT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `community_event_status_idx` (`status`),
  INDEX `community_event_organizer_id_idx` (`organizer_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
